name: Exemplo de CI # Nome da ação

on:
  pull_request: # Evento que irá disparar a ação
    branches: [ master ] # Branch que irá disparar a ação
    types: [opened, reopened]
jobs:
  build: # Trabalhos a serem executados
    runs-on: ubuntu-latest # Sistema operacional a ser utilizado
    steps: # Passos a serem executados
      - name: Checkout code # Nome do passo, nesse caso, clonar o repositório
        uses: actions/checkout@v4 # action escolhida para clonar o repositório

      - name: Set up JDK 17 # Nome do passo, nesse caso, configurar o JDK 17
        uses: actions/setup-java@v4 # action escolhida para configurar o JDK
        with: # Configurações da action
          distribution: 'temurin' # Distribuição do JDK
          java-version: '17' # Versão do JDK

      - name: Build with Maven # Nome do passo, nesse caso, buildar com Maven
        run: mvn -B package -DskipTests # Comando a ser executado
  test: # Novo trabalho para executar os testes
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Test with Maven
        run: mvn test